//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example1
{
    
    internal partial class Resource2
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource2.manager == null))
                {
                    Resource2.manager = new System.Resources.ResourceManager("Example1.Resource2", typeof(Resource2).Assembly);
                }
                return Resource2.manager;
            }
        }
        internal static System.Drawing.Bitmap GetBitmap(Resource2.BitmapResources id)
        {
            return ((System.Drawing.Bitmap)(ResourceManager.GetObject(((short)(id)))));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            randall3hrs = 1168,
            randallF1 = 3163,
            bird4 = 20225,
            bird1 = 20228,
            bird3 = 20230,
            bird2 = 20231,
        }
    }
}
